# Generated by Django 5.2.7 on 2025-10-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_proveedor',
            field=models.IntegerField(choices=[(1020, '1020- Carnes Y Productos de Origen Animal'), (2030, '2030- Lacteos y Derivados'), (3040, '3040- Electronica y Accesorios'), (4050, '4050- Ropa y Calzado'), (5060, '5060- Articulos de Hogar'), (6070, '6070- Articulos de Deporte'), (7080, '7080- Suministros de Higiene y Belleza'), (8090, '8090- Productos Varios'), (0, 'N/A')], default=0),
        ),
    ]
